<h>Generate random matrices of size n × n where n = 100, 200, . . . , 1000. Also generate a random b ∈ Rn for each case.Perform Gaussian Elimination with and without pivoting for each of the 10 cases above. Report the number of additions, divisions and multiplications for each case in the form of a table. No need to write matrices<h>

In [ ]:
import import_ipynb
import time
import numpy as np
import CalculateComputeTime
from CalculateComputeTime import *
import GenerateRandomMatrices
from GenerateRandomMatrices import *
import GaussEliminationOperationCount
from GaussEliminationOperationCount import *
import GaussElimination
from GaussElimination import *
import GaussEliminationwithPartialPivoting
from GaussEliminationwithPartialPivoting import *


# declare matrix size nxn
n = 1000
# declare significant digits
dS = 5
# declare high and low value for random matrix or vector generation
high = 10
low = 0
# step-1: Generate randon matrix with size nxn 
A = generateRandomMatrix(high,low,n,n,dS)
# step-2: Generate randon vector with size nx1 
b = generateRandomVector(high,low,n,dS)

# perform Gauss Elimination with pivoting with 5S arithmetic rounding
print("Gauss Elimination with pivoting ::")
# Also compute execution time
time_start = time.perf_counter()
# step-3: perform Gauss Forward Elimination 
B,g = Cal_FE_Pivot(A,b,dS)
# step-4: perform Gauss Back Substitution 
x2= Back_Subs_Pivot(B,g,dS)
time_elapsed = round_to_n((time.perf_counter() - time_start),dS)
print(f"GE with pivoting execution time in seconds: {time_elapsed}")
# step-5: display solution x where Ax =b
#print("The solution is:: ",x2)
# step-6: compute Gauss Elimination operation count
aDictionary = GaussEliminationOperationCount(n)

#print("Addition time taken:: ",aDictionary['addition']*singleadditiontime)
#print("Multiplication time taken :: ",aDictionary['multiplication']*singlemultiplicationtime)
#print("Divison time taken :: ",aDictionary['divison']*singltdivisontime)


# perform Gauss Elimination without pivoting with 5S arithmetic rounding
print("Gauss Elimination without pivoting ::")
# step-3: perform Gauss Forward Elimination
# Also compute execution time
time_start = time.perf_counter()
B,g = Cal_FE(A,b,dS)
# step-4: perform Gauss Back Substitution 
x1= Back_Subs(B,g,dS)
time_elapsed = round_to_n((time.perf_counter() - time_start),dS)
print(f"GE without pivoting execution time in seconds: {time_elapsed}")
# step-5: display solution x where Ax =b
#print("The solution is:: ",x1)
# step-6: compute Gauss Elimination operation count
aDictionary = GaussEliminationOperationCount(n)

#step-7: compute theoretical time taken
additionTime = aDictionary['addition']*singleAdditionTime()
multiplicationTime = aDictionary['multiplication']*singleMultiplicationTime()
divisonTime = aDictionary['divison']*singleDivisonTime()
totalTime = round_to_n((additionTime + multiplicationTime + divisonTime),dS)
print("Theoretical time taken ::", totalTime)



importing Jupyter notebook from CalculateComputeTime.ipynb
Time taken for a single addition in seconds is:  3.910848800000011e-08
Time taken for a single multiplication in seconds is:   4.581844700000026e-08
Time taken for a single divison in seconds is:   4.525174400000065e-08
importing Jupyter notebook from GenerateRandomMatrices.ipynb
importing Jupyter notebook from Utility.ipynb
importing Jupyter notebook from GaussEliminationOperationCount.ipynb
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Gauss Elimination total addition operation count::  11
Gauss Elimination total multiplicatin operation count::  11
Gauss Elimination total divison operation count::  6
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
importing Jupyter notebook from GaussElimination.ipynb
A Matrix::
 [[  4.3   0.2  -3.7]
 [-11.5  -2.    5.5]
 [ 17.7   1.8 -12.3]]
b vector::
 [ 1 -1  1]
Solution :: [ 10000. -30001.  10000.]
importing Jupyter notebook from GaussEliminationwithPartialPivoting.ipynb
A Matrix::
 [[ 0.